#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld -- "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, at most MAX_IGNORED=4.
MAX_IGNORED=4
count=0
for flag in "$@"; do
    case $flag in
        --) break ;;
        -*) count=$((count + 1));;
        *)  break ;;
    esac
    if [ $count -ge $MAX_IGNORED ]; then
        break
    fi
done

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $POSIXLY_CORRECTLY_REMAINING_ARGS

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum ignored=4.
count=0
for arg in "$@"; do
    case $arg in
        --) break ;;
        -*) count=$((count + 1));;
        *)  break ;;
    esac
    if [ $count -ge $MAX_IGNORED ]; then
        break
    fi
done

# Collect all arguments for the java command;
#   * $1-$MAX_IGNORED hold the options that must be passed before the main class
#   * the remaining args are passed to the main class
#   * store them into an array for later use
ARGS=()
count=0
for arg in "$@"; do
    case $arg in
        --)
            shift
            break
            ;;
        -*)
            count=$((count + 1))
            ;;
        *)
            break
            ;;
    esac
    if [ $count -ge $MAX_IGNORED ]; then
        break
    fi
    ARGS+=("$arg")
done

# Collect all remaining arguments after the options
ARGS+=("$@")

# Determine the classpath from the gradle-wrapper.jar
GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$GRADLE_WRAPPER_JAR" ] ; then
    die "ERROR: Could not find gradle-wrapper.jar in $GRADLE_WRAPPER_JAR"
fi

# Construct the classpath
CLASSPATH="$GRADLE_WRAPPER_JAR"

# Determine the main class
GRADLE_MAIN_CLASS=org.gradle.wrapper.GradleWrapperMain

# Construct the command line
CMD=("$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    $GRADLE_MAIN_CLASS \
    "${ARGS[@]}")

exec "${CMD[@]}"
